name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm libbpf-dev linux-headers-$(uname -r)
    
    - name: Build for multiple architectures
      run: |
        # Build for x86_64
        make clean
        make all
        mv flowmonitor flowmonitor-linux-amd64
        
        # Build eBPF object
        cp fffa.bpf.o fffa-linux-x86_64.bpf.o
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          flowmonitor-linux-amd64
          fffa-linux-x86_64.bpf.o
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
